name: stocks_up_down_monitor
run-name: ${{ github.actor }} is monitoring stock list
on: [push]
on:
  schedule:
    - cron: '0/5 1,2,3,5,6,7,13,14,15,16,17,18,19 * * 1-5'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: pip install -r requirements.txt
      - name: togo
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY}}
          DATABASE_ID: ${{ secrets.DATABASE_ID}}
          NOTICE_EMAIL_TO: ${{ secrets.NOTICE_EMAIL_TO}}
          NOTICE_EMAIL_FROM: ${{ secrets.NOTICE_EMAIL_FROM}}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD}}
        run: python stock_monitor.py

